UPDATE T_USER

SET BIRTHDAY　= 
    case USER_ID
    WHEN "AISHIDA" THEN "1997/1/7"
    WHEN "MMIKI" THEN "1999/10/8"
  END
  
, SENIORITY = 
    case USER_ID
    WHEN "AISHIDA" THEN 10
    WHEN "MMIKI" THEN 11
  END
  
, DELET_FLG = 
    case USER_ID
    WHEN "AISHIDA" THEN "1"
  END

WHERE USER_ID IN ("AISHIDA","MMIKI");