UPDATE T_USER

SET BIRTHDAY = 
    CASE USER_ID
    WHEN "AISHIDA" THEN "1997/1/7"
    WHEN "MMIKI" THEN "1999/10/8"
  END
  
, SENIORITY = 
    CASE USER_ID
    WHEN "AISHIDA" THEN 10
    WHEN "MMIKI" THEN 11
  END
  
, DELET_FLG = 
    CASE USER_ID
    WHEN "AISHIDA" THEN "1"
    WHEN "MMIKI" THEN "0"
  END

WHERE USER_ID IN ("AISHIDA","MMIKI");